version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  node-backend:
    build:
      context: .
      dockerfile: ./node-backend/Dockerfile
    ports:
      - "3100:3100"
    environment:
      PORT: 3100
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
      JWT_SECRET: your_jwt_secret_key
      GO_BACKEND_URL: http://go-backend:4100
    depends_on:
      - db

  go-backend:
    build: ./go-backend
    ports:
      - "4100:4100"
    environment:
      PORT: 4100
      DATABASE_URL: postgres://user:password@db:5432/mydatabase?sslmode=disable
      JWT_SECRET: your_jwt_secret_key
    depends_on:
      - db

volumes:
  db_data:
